def foo
	puts "ohai"
end

# Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis dolor blandit, luctus est et, luctus neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce posuere convallis purus, vel dapibus massa gravida at. Aenean dapibus risus erat, elementum condimentum ligula fermentum nec. Phasellus placerat nulla sed dui mattis rutrum. Sed aliquam aliquam nulla, vel sodales felis finibus vitae. Aenean iaculis eget ipsum vel consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer vel pretium nulla. Praesent nibh erat, ullamcorper at euismod ac, viverra a justo. Vestibulum lacinia cursus ex ut tincidunt.
# 	Nam bibendum lacinia molestie. Duis molestie nulla et elit maximus aliquet. Morbi blandit lectus sit amet ornare condimentum. Sed semper eu risus ac malesuada. Aenean eu euismod quam. Quisque sed suscipit justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In eros turpis, molestie ut pharetra vel, luctus nec leo. Sed at fringilla arcu, eu maximus justo. Ut odio ex, rhoncus eu dui vitae, condimentum lacinia mauris. Praesent at ante dapibus magna sagittis maximus. Aliquam erat volutpat. Sed commodo magna vel metus tempor, vel condimentum lorem ullamcorper. Quisque nisi elit, luctus eu pretium eu, ultrices sed justo. Praesent eros neque, luctus nec arcu a, ultrices vehicula justo. Integer libero arcu, sollicitudin sed elit mollis, pharetra lobortis odio.
# 		Maecenas fringilla scelerisque odio non forevis. Aenean tempor porttitor nisi id lacinia. Duis commodo augue in ante viverra, eu pharetra ligula pretium. Aenean ac erat felis. Sed sollicitudin, est nec fermentum sagittis, purus purus viverra orci, non commodo nisi velit sed ligula. Curabitur pellentesque elementum tortor eget interdum. Fusce a ante suscipit, porta ipsum a, blandit diam. Ut eget nulla sed felis lacinia rhoncus non eu erat. Mauris porttitor lorem libero. Cras malesuada libero orci, interdum cursus lorem egestas in. Nam venenatis posuere nunc, eu ultrices leo pharetra sit amet. Donec fringilla elit ac urna viverra pharetra. Mauris hendrerit ex non nibh interdum, non ornare massa finibus.
# 	Nulla dictum eget dui et aliquam. Cras libero nisl, dictum at turpis aliquet, fringilla tempus augue. Suspendisse consequat mi sed lectus malesuada, ac volutpat mi mollis. Pellentesque quis viverra mi, vel ultrices erat. Mauris bibendum magna vel ultrices fermentum. Mauris nisl urna, sodales vitae sapien vitae, dictum euismod purus. Vivamus volutpat vel dolor et posuere. Sed euismod, felis sit amet vehicula tristique, massa risus consectetur mauris, eu iaculis justo magna sit amet dui. Ut urna purus, faucibus nec odio id, pharetra aliquam velit. Duis sit amet leo id ligula posuere pharetra. Cras viverra tellus vel nisi sagittis, sit amet blandit justo fringilla. Cras tempor laoreet scelerisque. Vivamus pharetra augue in neque interdum cursus. In fringilla lacus ut lectus pretium, et pharetra nulla condimentum. Maecenas commodo augue posuere mollis dictum.
# Nam eu sem ut metus fringilla ornare. Sed porta euismod massa non eleifend. Ut commodo nisl erat, eget elementum leo aliquam sed. Vestibulum accumsan tincidunt arcu, vel tincidunt tellus blandit faucibus. Pellentesque aliquam interdum risus et mollis. Aenean ac fringilla velit, sed sollicitudin elit. Nullam bibendum facilisis libero, ac vestibulum turpis pulvinar elementum.

